### ISSUE TITLE
not released yet?

### ISSUE THREAD

**Issue by MichaelSp** [opal/opal-rspec-rails#5]
There is no official release yet, or am I missing something?

https://rubygems.org/search?utf8=%E2%9C%93&query=opal-rspec-rails

are there any blockers preventing a release?

**Comment by wied03** [comment]
@MichaelSp - opal-rails was forked into 2 separate GEMs, this being one of them. I think neither @elia nor myself have had time to catch up though. I believe opal-rspec-rails was mainly waiting for  opal-rspec 0.6, which is out now but @elia would need to confirm what else was on the TODO list or opal-rspec-rails.

**Comment by MichaelSp** [comment]
thanks for clarification :ok_hand:
